### ISSUE TITLE
您好请教一下

### ISSUE THREAD

**Issue by ddjj7** [YungGuo08/WebSpider#1]
您好想请教一下，加速乐的加密算法，就下面这一段，是如何发现的？
clearance = data['bts'][0] + data['chars'][i] + data['chars'][j] + data['bts'][1]
。。。
if result == data['ct']:
                return clearance
比较好奇，谢谢。。。

**Comment by YungGuo08** [comment]
这个是通过抓包分析网站请求得到的，具体抓包过程有在csdn文章中写。网站响应的js代码是经过混淆的，解混淆后就可以得到js加密函数。

**Comment by ddjj7** [comment]
恩是的，我也是通过抓包拿到了两次521的返回js，但是解混淆之后还是特复杂的一个js，大量如下的这种函数和变量定义：
function _0x161e53(_0x4b5319, _0x4480c4, _0x447b67) {
    return _0x4b5319 & _0x4480c4 ^ ~_0x4b5319 & _0x447b67;
  }
到了这一步以后您就是靠硬读js代码分析出来了的吗。。

**Comment by YungGuo08** [comment]
对，解混淆后变量名还是混淆的，不利于解读，这些混淆变量名使用笨方法直接把相同的名字替换成利于解读的单词或者字母就行。或者不替换也行，只要找到关键代码段，复制出来用工具进行测试，然后查漏补缺，也能得到最终加密代码。

**Comment by ddjj7** [comment]
好的明白了，谢谢
